version: "3.6"
services:
  native-apps:
    image: native-apps
    container_name: native-apps
    volumes:
      - ./native_apps:/opt/native_apps
      - ./data:/opt/data
  jupyterlab-apps:
    image: jupyterlab-apps
    container_name: jupyterlab-apps
    ports:
      - 8888:8888
    volumes:
      - ./jupyterlab_apps:/opt/jupyterlab_apps
      - ./data:/opt/data
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8081:8080
      - 7077:7077
    volumes:
      - ./data:/opt/data
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - ./data:/opt/data
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8083:8081
    volumes:
      - ./data:/opt/data
    depends_on:
      - spark-master
